### ISSUE TITLE
gem に関して

### ISSUE THREAD

**Issue by xxmeiyingxx** [katokaisya/bungukato#10]
導入したいgemがあれば・・・

**Comment by xxmeiyingxx** [comment]
個人的には
schemaをmodelに書き出してくれる『 annotate 』は欲しいかなと思ってます

**Comment by xxmeiyingxx** [comment]
結果的にWikiにある通りで。
独自機能等で追加する場合は記述してください

**Comment by hirosekaoru** [comment]
modelsのuser.rbでhas_secure_passwordが使えるようにgemファイルの#gem 'bcrypt'のコメントを外しました。bundleお願いします。
